- name: spring boot deploy

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name : Spring Boot Builder
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        -
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Make Directory for deliver
          run: mkdir deploy

      - name: Copy Jar
          run: cp ./build/libs/*.jar ./deploy/

      - name: Make zip file
          run: zip -r -qq -j ./springboot-intro-build.zip ./deploy

      - name: S3 upload
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp \
          --recursive \
          --region ap-northeast-2 \
          deploy s3://musinsa-watcher