name: spring boot deploy-dev

on:
  push:
    branches: [ backend-dev ]

jobs:
  build:
    name: Spring Boot Builder
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Make Directory deploy
        run: mkdir -p deploy

      - name: Move deploy script
        run: cp scripts/*.sh ./deploy/

      - name: Move nginx.conf
        run: cp nginx.conf ./deploy/

      - name: Move docker-compose.yml
        run: cp docker-compose.yml ./deploy/

      - name: Copy Jar
        run: cp build/libs/*.jar ./app.jar

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          push: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_REPOSITORY }}
          tags: latest

      - name: Dev sever scp deploy folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USERNAME }}
          password: ${{ secrets.DEV_SERVER_PASSWORD }}
          port: ${{ secrets.DEV_SERVER_PORT }}
          source: "./deploy/*"
          target: "~/"
          overwrite: true

      - name: Dev sever deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USERNAME }}
          password: ${{ secrets.DEV_SERVER_PASSWORD }}
          port: ${{ secrets.DEV_SERVER_PORT }}
          script: |
            cd deploy
            sudo bash deploy.sh

      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_URL_DEPLOY }} # required
        if: ${{ always() }}