name: vue-builder
on:
  push:
    branches: [front-dev]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install
        working-directory: frontend

      - name: Build
        run: npm run build
        working-directory: frontend

      - name: Install Dependencies
        run: npm install
        working-directory: frontend-mobile

      - name: Build
        run: npm run build
        working-directory: frontend-mobile

      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_URL_BUILD }} # required
        if: ${{ always() }}